route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
    - to: 'esmaeelsiaahlooie@gmail.com'
      from: 'esmaeelsiaahlooie@gmail.com'
      smarthost: smtp.gmail.com:587
      auth_username: 'esmaeelsiaahlooie@gmail.com'
      auth_identity: 'esmaeelsiaahlooie'
      auth_password: 'xnjjqoihlbrljpwh'
