route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
    - to: 'sample@gmail.com'
      from: 'sample@gmail.com'
      smarthost: smtp.gmail.com:587
      auth_username: 'sample@gmail.com'
      auth_identity: 'username'
      auth_password: 'password'
